version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
  
  test:
    build:
      context: .
      dockerfile: test.Dockerfile
    volumes:
      - .:/code
